### ISSUE TITLE
Unclear How to Add Question Theme

### ISSUE THREAD

**Issue by ceprdata** [adamzammit/LimeSurvey-Signature-Question#4]
I'm using LimeSurvey Community Edition Version 6.4.0+231218 and the instructions for creating a signature question don't seem to apply to this version. I was able to install it with no issues, and the question theme appears as a User Theme. However, within a survey, there is no option to adjust a question theme on a Short Free-text-type question. Am I missing something?

EDIT: I found the "Signature Pad" question type, but when I preview, it's just a text input.

**Comment by adamzammit** [comment]
Thank you - I've updated the README to make it more clear how to install and use.

I'm not sure why you are just seeing text input when you preview. Can you confirm you used the latest release (1.0.3)?

**Comment by ceprdata** [comment]
According to config.xml, it's 1.0.3.

UPDATE: From what I can tell, even though the question type is Signature Pad, it's displaying a Short Free Text. It's not creating a canvas, only an input field. And since there is no element with the "signature-pad" id, nothing is happening.

SOLUTION: I discovered the issue. I logged into the server and discovered that the installer was creating an unnecessary directory hierarchy. It installed the theme in upload/themes/question/signature/signature/survey/...[NOTE THE SECOND UNNECESSARY signature FOLDER]. When I moved everything one directory up, it worked.

**Comment by adamzammit** [comment]
thanks for following up with this. I was able to reproduce this issue by downloading the source code ZIP file instead of the release ZIP file, and then uploading that as the theme.

I'll update the docs to confirm that the release file (such as: https://github.com/adamzammit/LimeSurvey-Signature-Question/releases/download/1.0.3/LimeSurvey-Signature-Question-1.0.3.zip ) needs to be downloaded if you want to upload it to LS as a new question theme.
